# Generated by Django 2.2 on 2020-02-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoviesComments',
            new_name='PostsComments',
        ),
    ]
